### ISSUE TITLE
Cannot find module '_isMockFunction'

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#18324]
-- Description
Starting with VS Code 1.74.1, I get the following error when running tests using Jest. It works with VS Code 1.73.1
```
 Cannot find module '_isMockFunction'
    Require stack:
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
   ```

-- Reproduction
1. Clone https://www.github.com/idahogurl/vs-code-prettier-eslint
2. Run `yarn` to install node modules
3. Run `yarn test`

This may be a VS Code issue.
